# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'task2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(501, 184)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.lineEdit_filename = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_filename.setReadOnly(True)
        self.lineEdit_filename.setObjectName("lineEdit_filename")
        self.horizontalLayout.addWidget(self.lineEdit_filename)
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout.addWidget(self.radioButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.lineEdit_output = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_output.setReadOnly(True)
        self.lineEdit_output.setObjectName("lineEdit_output")
        self.horizontalLayout_2.addWidget(self.lineEdit_output)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_dialog1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_dialog1.setObjectName("pushButton_dialog1")
        self.horizontalLayout_3.addWidget(self.pushButton_dialog1)
        self.pushButton_dialog2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_dialog2.setObjectName("pushButton_dialog2")
        self.horizontalLayout_3.addWidget(self.pushButton_dialog2)
        self.pushButton_dialog3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_dialog3.setObjectName("pushButton_dialog3")
        self.horizontalLayout_3.addWidget(self.pushButton_dialog3)
        self.pushButton_dialog4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_dialog4.setObjectName("pushButton_dialog4")
        self.horizontalLayout_3.addWidget(self.pushButton_dialog4)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 501, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("MainWindow", "Открыть файл"))
        self.radioButton.setText(_translate("MainWindow", "Полный путь?"))
        self.pushButton.setText(_translate("MainWindow", "Получить строку"))
        self.pushButton_dialog1.setText(_translate("MainWindow", "1"))
        self.pushButton_dialog2.setText(_translate("MainWindow", "2"))
        self.pushButton_dialog3.setText(_translate("MainWindow", "3"))
        self.pushButton_dialog4.setText(_translate("MainWindow", "PushButton"))
